// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder createBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.create");
		return builder;
	}

	public static void create(IContext context)
	{
		createBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder myFirstLogicBuilder(
		myfirstmodule.proxies.ManufacturingOrder _manufacturingOrder
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.MyFirstLogic");
		builder = builder.withParam("ManufacturingOrder", _manufacturingOrder);
		return builder;
	}

	public static void myFirstLogic(
		IContext context,
		myfirstmodule.proxies.ManufacturingOrder _manufacturingOrder
	)
	{
		myFirstLogicBuilder(
				_manufacturingOrder
			)
			.execute(context);
	}
}
