// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Container implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject containerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Container";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ContainerName("ContainerName"),
		Quantity("Quantity"),
		owner_type("owner_type"),
		Start_reason("Start_reason"),
		Level("Level"),
		workflow("workflow"),
		WorkFlowRevision("WorkFlowRevision");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Container(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Container(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject containerMendixObject)
	{
		if (containerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!containerMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.containerMendixObject = containerMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Container initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Container(context, mendixObject);
	}

	public static myfirstmodule.proxies.Container load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Container.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Container> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Container.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ContainerName
	 */
	public final java.lang.String getContainerName()
	{
		return getContainerName(getContext());
	}

	/**
	 * @param context
	 * @return value of ContainerName
	 */
	public final java.lang.String getContainerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContainerName.toString());
	}

	/**
	 * Set value of ContainerName
	 * @param containername
	 */
	public final void setContainerName(java.lang.String containername)
	{
		setContainerName(getContext(), containername);
	}

	/**
	 * Set value of ContainerName
	 * @param context
	 * @param containername
	 */
	public final void setContainerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String containername)
	{
		getMendixObject().setValue(context, MemberNames.ContainerName.toString(), containername);
	}

	/**
	 * @return value of Quantity
	 */
	public final java.math.BigDecimal getQuantity()
	{
		return getQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of Quantity
	 */
	public final java.math.BigDecimal getQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Quantity.toString());
	}

	/**
	 * Set value of Quantity
	 * @param quantity
	 */
	public final void setQuantity(java.math.BigDecimal quantity)
	{
		setQuantity(getContext(), quantity);
	}

	/**
	 * Set value of Quantity
	 * @param context
	 * @param quantity
	 */
	public final void setQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal quantity)
	{
		getMendixObject().setValue(context, MemberNames.Quantity.toString(), quantity);
	}

	/**
	 * Get value of owner_type
	 * @param owner_type
	 */
	public final myfirstmodule.proxies.owner_type getowner_type()
	{
		return getowner_type(getContext());
	}

	/**
	 * @param context
	 * @return value of owner_type
	 */
	public final myfirstmodule.proxies.owner_type getowner_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.owner_type.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.owner_type.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of owner_type
	 * @param owner_type
	 */
	public final void setowner_type(myfirstmodule.proxies.owner_type owner_type)
	{
		setowner_type(getContext(), owner_type);
	}

	/**
	 * Set value of owner_type
	 * @param context
	 * @param owner_type
	 */
	public final void setowner_type(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.owner_type owner_type)
	{
		if (owner_type != null) {
			getMendixObject().setValue(context, MemberNames.owner_type.toString(), owner_type.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.owner_type.toString(), null);
		}
	}

	/**
	 * Get value of Start_reason
	 * @param start_reason
	 */
	public final myfirstmodule.proxies.start_reason getStart_reason()
	{
		return getStart_reason(getContext());
	}

	/**
	 * @param context
	 * @return value of Start_reason
	 */
	public final myfirstmodule.proxies.start_reason getStart_reason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Start_reason.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.start_reason.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Start_reason
	 * @param start_reason
	 */
	public final void setStart_reason(myfirstmodule.proxies.start_reason start_reason)
	{
		setStart_reason(getContext(), start_reason);
	}

	/**
	 * Set value of Start_reason
	 * @param context
	 * @param start_reason
	 */
	public final void setStart_reason(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.start_reason start_reason)
	{
		if (start_reason != null) {
			getMendixObject().setValue(context, MemberNames.Start_reason.toString(), start_reason.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Start_reason.toString(), null);
		}
	}

	/**
	 * Get value of Level
	 * @param level
	 */
	public final myfirstmodule.proxies.level getLevel()
	{
		return getLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of Level
	 */
	public final myfirstmodule.proxies.level getLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Level.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.level.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Level
	 * @param level
	 */
	public final void setLevel(myfirstmodule.proxies.level level)
	{
		setLevel(getContext(), level);
	}

	/**
	 * Set value of Level
	 * @param context
	 * @param level
	 */
	public final void setLevel(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.level level)
	{
		if (level != null) {
			getMendixObject().setValue(context, MemberNames.Level.toString(), level.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Level.toString(), null);
		}
	}

	/**
	 * @return value of workflow
	 */
	public final java.lang.String getworkflow()
	{
		return getworkflow(getContext());
	}

	/**
	 * @param context
	 * @return value of workflow
	 */
	public final java.lang.String getworkflow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.workflow.toString());
	}

	/**
	 * Set value of workflow
	 * @param workflow
	 */
	public final void setworkflow(java.lang.String workflow)
	{
		setworkflow(getContext(), workflow);
	}

	/**
	 * Set value of workflow
	 * @param context
	 * @param workflow
	 */
	public final void setworkflow(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workflow)
	{
		getMendixObject().setValue(context, MemberNames.workflow.toString(), workflow);
	}

	/**
	 * @return value of WorkFlowRevision
	 */
	public final java.lang.String getWorkFlowRevision()
	{
		return getWorkFlowRevision(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkFlowRevision
	 */
	public final java.lang.String getWorkFlowRevision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkFlowRevision.toString());
	}

	/**
	 * Set value of WorkFlowRevision
	 * @param workflowrevision
	 */
	public final void setWorkFlowRevision(java.lang.String workflowrevision)
	{
		setWorkFlowRevision(getContext(), workflowrevision);
	}

	/**
	 * Set value of WorkFlowRevision
	 * @param context
	 * @param workflowrevision
	 */
	public final void setWorkFlowRevision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workflowrevision)
	{
		getMendixObject().setValue(context, MemberNames.WorkFlowRevision.toString(), workflowrevision);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return containerMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Container that = (myfirstmodule.proxies.Container) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
