// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum level
{
	_1("c6fd55d3-1fff-48ab-94ce-bda546f6fc04"),
	_2("cbaf27dd-eeb6-4a44-a2db-a72b5aece00e"),
	_3("138ae8aa-955c-49af-a636-6434048843b6"),
	_4("4f3ded97-017f-4457-80a1-7a709a442a20");

	private final java.lang.String i18nCaptionKey;
	
	private level(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
