// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class ManufacturingOrder implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject manufacturingOrderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.ManufacturingOrder";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OrderNumber("OrderNumber"),
		Priority("Priority"),
		ReleaseDate("ReleaseDate"),
		PlannedStartDate("PlannedStartDate"),
		PlannedCompletionDate("PlannedCompletionDate"),
		Quantity("Quantity"),
		InProgressQuantity("InProgressQuantity"),
		status("status");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ManufacturingOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ManufacturingOrder(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject manufacturingOrderMendixObject)
	{
		if (manufacturingOrderMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!manufacturingOrderMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.manufacturingOrderMendixObject = manufacturingOrderMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.ManufacturingOrder initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.ManufacturingOrder(context, mendixObject);
	}

	public static myfirstmodule.proxies.ManufacturingOrder load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.ManufacturingOrder.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.ManufacturingOrder> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.ManufacturingOrder.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of OrderNumber
	 */
	public final java.lang.String getOrderNumber()
	{
		return getOrderNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderNumber
	 */
	public final java.lang.String getOrderNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OrderNumber.toString());
	}

	/**
	 * Set value of OrderNumber
	 * @param ordernumber
	 */
	public final void setOrderNumber(java.lang.String ordernumber)
	{
		setOrderNumber(getContext(), ordernumber);
	}

	/**
	 * Set value of OrderNumber
	 * @param context
	 * @param ordernumber
	 */
	public final void setOrderNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ordernumber)
	{
		getMendixObject().setValue(context, MemberNames.OrderNumber.toString(), ordernumber);
	}

	/**
	 * Get value of Priority
	 * @param priority
	 */
	public final myfirstmodule.proxies.priority getPriority()
	{
		return getPriority(getContext());
	}

	/**
	 * @param context
	 * @return value of Priority
	 */
	public final myfirstmodule.proxies.priority getPriority(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Priority.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.priority.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Priority
	 * @param priority
	 */
	public final void setPriority(myfirstmodule.proxies.priority priority)
	{
		setPriority(getContext(), priority);
	}

	/**
	 * Set value of Priority
	 * @param context
	 * @param priority
	 */
	public final void setPriority(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.priority priority)
	{
		if (priority != null) {
			getMendixObject().setValue(context, MemberNames.Priority.toString(), priority.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Priority.toString(), null);
		}
	}

	/**
	 * @return value of ReleaseDate
	 */
	public final java.util.Date getReleaseDate()
	{
		return getReleaseDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ReleaseDate
	 */
	public final java.util.Date getReleaseDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ReleaseDate.toString());
	}

	/**
	 * Set value of ReleaseDate
	 * @param releasedate
	 */
	public final void setReleaseDate(java.util.Date releasedate)
	{
		setReleaseDate(getContext(), releasedate);
	}

	/**
	 * Set value of ReleaseDate
	 * @param context
	 * @param releasedate
	 */
	public final void setReleaseDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date releasedate)
	{
		getMendixObject().setValue(context, MemberNames.ReleaseDate.toString(), releasedate);
	}

	/**
	 * @return value of PlannedStartDate
	 */
	public final java.util.Date getPlannedStartDate()
	{
		return getPlannedStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of PlannedStartDate
	 */
	public final java.util.Date getPlannedStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PlannedStartDate.toString());
	}

	/**
	 * Set value of PlannedStartDate
	 * @param plannedstartdate
	 */
	public final void setPlannedStartDate(java.util.Date plannedstartdate)
	{
		setPlannedStartDate(getContext(), plannedstartdate);
	}

	/**
	 * Set value of PlannedStartDate
	 * @param context
	 * @param plannedstartdate
	 */
	public final void setPlannedStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date plannedstartdate)
	{
		getMendixObject().setValue(context, MemberNames.PlannedStartDate.toString(), plannedstartdate);
	}

	/**
	 * @return value of PlannedCompletionDate
	 */
	public final java.util.Date getPlannedCompletionDate()
	{
		return getPlannedCompletionDate(getContext());
	}

	/**
	 * @param context
	 * @return value of PlannedCompletionDate
	 */
	public final java.util.Date getPlannedCompletionDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PlannedCompletionDate.toString());
	}

	/**
	 * Set value of PlannedCompletionDate
	 * @param plannedcompletiondate
	 */
	public final void setPlannedCompletionDate(java.util.Date plannedcompletiondate)
	{
		setPlannedCompletionDate(getContext(), plannedcompletiondate);
	}

	/**
	 * Set value of PlannedCompletionDate
	 * @param context
	 * @param plannedcompletiondate
	 */
	public final void setPlannedCompletionDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date plannedcompletiondate)
	{
		getMendixObject().setValue(context, MemberNames.PlannedCompletionDate.toString(), plannedcompletiondate);
	}

	/**
	 * @return value of Quantity
	 */
	public final java.math.BigDecimal getQuantity()
	{
		return getQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of Quantity
	 */
	public final java.math.BigDecimal getQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Quantity.toString());
	}

	/**
	 * Set value of Quantity
	 * @param quantity
	 */
	public final void setQuantity(java.math.BigDecimal quantity)
	{
		setQuantity(getContext(), quantity);
	}

	/**
	 * Set value of Quantity
	 * @param context
	 * @param quantity
	 */
	public final void setQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal quantity)
	{
		getMendixObject().setValue(context, MemberNames.Quantity.toString(), quantity);
	}

	/**
	 * @return value of InProgressQuantity
	 */
	public final java.math.BigDecimal getInProgressQuantity()
	{
		return getInProgressQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of InProgressQuantity
	 */
	public final java.math.BigDecimal getInProgressQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.InProgressQuantity.toString());
	}

	/**
	 * Set value of InProgressQuantity
	 * @param inprogressquantity
	 */
	public final void setInProgressQuantity(java.math.BigDecimal inprogressquantity)
	{
		setInProgressQuantity(getContext(), inprogressquantity);
	}

	/**
	 * Set value of InProgressQuantity
	 * @param context
	 * @param inprogressquantity
	 */
	public final void setInProgressQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal inprogressquantity)
	{
		getMendixObject().setValue(context, MemberNames.InProgressQuantity.toString(), inprogressquantity);
	}

	/**
	 * Get value of status
	 * @param status
	 */
	public final myfirstmodule.proxies.status getstatus()
	{
		return getstatus(getContext());
	}

	/**
	 * @param context
	 * @return value of status
	 */
	public final myfirstmodule.proxies.status getstatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.status.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of status
	 * @param status
	 */
	public final void setstatus(myfirstmodule.proxies.status status)
	{
		setstatus(getContext(), status);
	}

	/**
	 * Set value of status
	 * @param context
	 * @param status
	 */
	public final void setstatus(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.status status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.status.toString(), null);
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return manufacturingOrderMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.ManufacturingOrder that = (myfirstmodule.proxies.ManufacturingOrder) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
