// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class OrderDispatchHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject orderDispatchHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.OrderDispatchHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		containerName("containerName"),
		EnteredQuantity("EnteredQuantity"),
		AutoName("AutoName");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OrderDispatchHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected OrderDispatchHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject orderDispatchHelperMendixObject)
	{
		if (orderDispatchHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!orderDispatchHelperMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.orderDispatchHelperMendixObject = orderDispatchHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.OrderDispatchHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.OrderDispatchHelper(context, mendixObject);
	}

	public static myfirstmodule.proxies.OrderDispatchHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.OrderDispatchHelper.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.OrderDispatchHelper> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.OrderDispatchHelper.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of containerName
	 */
	public final java.lang.String getcontainerName()
	{
		return getcontainerName(getContext());
	}

	/**
	 * @param context
	 * @return value of containerName
	 */
	public final java.lang.String getcontainerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.containerName.toString());
	}

	/**
	 * Set value of containerName
	 * @param containername
	 */
	public final void setcontainerName(java.lang.String containername)
	{
		setcontainerName(getContext(), containername);
	}

	/**
	 * Set value of containerName
	 * @param context
	 * @param containername
	 */
	public final void setcontainerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String containername)
	{
		getMendixObject().setValue(context, MemberNames.containerName.toString(), containername);
	}

	/**
	 * @return value of EnteredQuantity
	 */
	public final java.lang.String getEnteredQuantity()
	{
		return getEnteredQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of EnteredQuantity
	 */
	public final java.lang.String getEnteredQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EnteredQuantity.toString());
	}

	/**
	 * Set value of EnteredQuantity
	 * @param enteredquantity
	 */
	public final void setEnteredQuantity(java.lang.String enteredquantity)
	{
		setEnteredQuantity(getContext(), enteredquantity);
	}

	/**
	 * Set value of EnteredQuantity
	 * @param context
	 * @param enteredquantity
	 */
	public final void setEnteredQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String enteredquantity)
	{
		getMendixObject().setValue(context, MemberNames.EnteredQuantity.toString(), enteredquantity);
	}

	/**
	 * @return value of AutoName
	 */
	public final java.lang.String getAutoName()
	{
		return getAutoName(getContext());
	}

	/**
	 * @param context
	 * @return value of AutoName
	 */
	public final java.lang.String getAutoName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AutoName.toString());
	}

	/**
	 * Set value of AutoName
	 * @param autoname
	 */
	public final void setAutoName(java.lang.String autoname)
	{
		setAutoName(getContext(), autoname);
	}

	/**
	 * Set value of AutoName
	 * @param context
	 * @param autoname
	 */
	public final void setAutoName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String autoname)
	{
		getMendixObject().setValue(context, MemberNames.AutoName.toString(), autoname);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return orderDispatchHelperMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.OrderDispatchHelper that = (myfirstmodule.proxies.OrderDispatchHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
