// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum owner_type
{
	production("a3b57b01-5e18-4edb-ae9f-7c8356598ebc"),
	quality("fae58ab7-4958-4758-98e8-6a5ff06a18e3"),
	logistics("37016a30-7bde-4057-a1e5-9adcb464e832"),
	supervisor("70b99ab7-d114-49b0-821b-153e838cd716");

	private final java.lang.String i18nCaptionKey;
	
	private owner_type(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
