// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum priority
{
	low("b88a3b49-0397-41e1-844d-7a6343cece73"),
	medium("7eb0af1f-f8cd-4988-bca8-13d34ebba50b"),
	high("9ae36ed6-eab3-4d3a-92ba-b46d96459674"),
	urgent("23b713b4-43bf-4240-bc3a-17dbc359ddba");

	private final java.lang.String i18nCaptionKey;
	
	private priority(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
