// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum start_reason
{
	Manual("e4e49abc-b7f0-4ddf-88a0-6eeb1e165f78"),
	production_order("967e29ea-b67d-4ba8-aa14-748a4c9ff81d"),
	testing("93eb97aa-fabf-4842-a1a0-2ca440dc94d1"),
	system_trigger("550756a9-1c45-4a58-8bc7-0023dafe7d8a"),
	rework("078a2e1d-edd2-473b-bf84-2f31fedb4c83");

	private final java.lang.String i18nCaptionKey;
	
	private start_reason(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
