// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum status
{
	in_progress("af44d86b-c83c-4e98-8fc9-975f487fc69f"),
	completed("d477c11d-8ddd-4de4-b570-cb603927d9b5"),
	created("980402cb-31ae-456e-9eb5-33cd93129508"),
	cancelled("5cd8fc3b-9ba9-4541-9d74-91749728206e");

	private final java.lang.String i18nCaptionKey;
	
	private status(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
